[package]
name = "kiteconnect"
version = "0.3.0"
authors = ["Joe Paul <joeirimpan@gmail.com>"]
description = "Async RUST API wrapper for kiteconnect APIs with WASM support"
license = "MIT"
repository = "https://github.com/zerodhatech/kiteconnect-rust"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core async dependencies
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.98"
url = "2.5.4"
log = "0.4"
async-trait = "0.1.88"
hex = "0.4"

# Native-specific dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.45.1", features = ["full"] }
reqwest = { version = "0.12.20", features = ["json", "stream"] }
sha2 = "0.10.9"
csv = "1.3.1"

# Optional WebSocket support for native
tokio-tungstenite = { version = "0.27.0", optional = true }
futures-util = { version = "0.3.31", optional = true }

# WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.12.20", features = ["json"], default-features = false }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "console",
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "Storage",
    "WebSocket",
    "MessageEvent",
    "ErrorEvent",
    "CloseEvent",
    "BinaryType",
    "Crypto",
    "SubtleCrypto",
] }
gloo-utils = "0.1"

[dev-dependencies]
mockito = "1.7.0"

# WASM test dependencies
[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.50"

[features]
default = ["native"]
native = []
wasm = []
websocket = ["tokio-tungstenite", "futures-util"]

# Examples for different targets
[[example]]
name = "connect_sample"
required-features = ["native"]

[[example]]
name = "async_connect_example" 
required-features = ["native"]

[[example]]
name = "wasm_example"
required-features = ["wasm"]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]
