[package]
name = "kiteconnect_rust"
version = "0.1.1"
authors = ["Joe Paul <joeirimpan@gmail.com>"]
description = "RUST API wrapper for kiteconnect APIs"
license = "MIT"
repository = "https://github.com/zerodhatech/kiteconnect-rust"

[dependencies]
reqwest = "0.8.1"
hyper = "0.11.6"
serde = "1.0.24"
serde_derive = "1.0.27"
serde_json = "1.0"
error-chain = "0.11.0"
rust-crypto = "0.2.36"

[dev-dependencies]
mockito = "0.9.0"
