[package]
name = "kiteconnect-rust"
version = "0.1.0"
authors = ["Joe Paul <joeirimpan@gmail.com>"]

[dependencies]
reqwest = "0.8.1"
hyper = "0.11.6"
serde = "*"
serde_derive = "*"
serde_json = "1.0"
error-chain = "0.11.0"
rust-crypto = "0.2.36"
